#! /bin/bash
# This software installation script is for CentOS
# You just need to hash out or remove any installation you don't want
# You can also add in additional software packages you like
 
#Updates
yum update -y yum
yum update -y
 
#Additional yum plugins
yum install -y yum-plugin-fastestmirror

#ELRepo for CentOS 7
rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
rpm -Uvh https://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm 

#EPEL Repo for CentOS 7
yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

#RPMFusion Repo for CentOS 7
sudo yum localinstall --nogpgcheck https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-7.noarch.rpm
 

yum update -y

 
#Installing Essential Utilities
yum install -y gparted
yum install -y gcc kernel-devel
yum install -y unrar
yum install -y wget
yum install -y smartmontools

#Terminal Emulator
#yum install -y terminator
#yum install -y guake

#Editor
yum install -y vim
yum install -y nano
#yum install -y emacs
#yum install -y kate

#Image Editor
yum install -y gimp
#yum install -y gthumb



# Download and install Google Software Public Signing Key
wget https://dl-ssl.google.com/linux/linux_signing_key.pub
sudo rpm --import linux_signing_key.pub
rm linux_signing_key.pub 

 
#Installing Media Players, DVD codec and Ripper
yum install -y vlc
yum install -y libdvdcss
yum update -y
yum install -y xine xine-lib-extras xine-lib-extras-freeworld

 
#End message
echo "Installation Complete"
